### PR TITLE
Solution for Issue #124

### PR DESCRIPTION
**Pull request by johnnyfreeman**
Like the title says: https://github.com/fuel/orm/issues/124

Note: My other pull request was closed and I can't figure out how to add this commit to that existing pull request (tried Googling, found nothing)

### CODE REVIEW

**Comment by WanWizard** [comment]
Implemented in https://github.com/fuel/orm/commit/34538bdd3c689f34b3b64826cefb8275d061c096

**Comment by johnnyfreeman** [comment]
No activity for 7 months and then you copy & paste it into your own commit?

I'm not trying to make a big deal about this, and maybe I'm the only one who feels this way, but it would be nice if the true author of the code to receive the "credit" for his work, even if it is just in the commit history.

I guess this is probably pointless... This is Fuel's repo, and you're entitled to accept (or copy & paste) pull requests however you want to. :)

Anyways, thanks for accepting!

**Comment by WanWizard** [comment]
Did I forget you in the comments? Oops, that wasn't intentional, my apologies. It's been a bit crazy today trying to cleanup all pull requests and issues for the release of 1.2.1.

I had to copy it as this pull request could no longer be merged. I added the link here so the commit referenced this pull request.

**Comment by johnnyfreeman** [comment]
Have you ever looked back at something you wrote yesterday and thought to yourself "Dang. Maybe I took that a little overboard?"? Lol! Thanks for being professional about it. Really! I feel like a total douchebag right now.

Believe me, I know how crazy hectic it can be trying to get ready for a new release. And it doesn't make it any easier when a _small_ contributor is riding you about something that isn't even a big deal. In retrospect, I should have said something like this:

> Hey, thanks for accepting! I see that my PR was no longer referencing the correct branch. So sorry about that! I would have preferred to be listed as the contributing author but it's not a big deal. :) 
> 
> Next time I'll take better responsibility for my pull requests and keep them up to date with the current dev branch.
> 
> Keep up the good work! It is much appreciated. :)

I do apologize that I didn't say that yesterday. And thanks for being cool about it!

**Comment by WanWizard** [comment]
No problem. Awaiting your next PR! :-)

**Pull request closed without merging**
