### PR TITLE
Moves config load call to be more reliable

### PR DESCRIPTION
**Pull request by emlynwest**

### CODE REVIEW

**Comment by WanWizard** [comment]
Did you encounter a situation where _init() isn't called?

**Comment by emlynwest** [comment]
I did, yes. I was not able to find out why it was not being called and thought it safer to load the config only where it's actually used.

**Comment by frankdejonge** [comment]
@stevewest better would be to find out why the init function isn't called and fix that, this shouldn't happen. Also this will decrece performance.

**Comment by emlynwest** [comment]
@FrenkyNet It would but I did look into it and was not able to find out why. I'll take another look later today though.

**Comment by frankdejonge** [comment]
I'm closing this one as this isn't the fix...

**Pull request closed without merging**
