### PR TITLE
model_soft::delete() probrems

### PR DESCRIPTION
**Pull request by takyam-git**
ｆｉｘ 2 probrems.
### probrem 1 : Model_Soft::delete() with belongs to field that not null and has foreign key.

https://github.com/fuel/orm/issues/263 <- this issue.

bd7b62e

Model_Parent and Model_Child are Model_Soft.
##### save a parent with a chlid.

``` php
<?php
$parent = Model_Parent::forge(array('name' => uniqid()));
$parent->children[] = Model_Child::forge(array('name' => uniqid()));
$parent->save(true, true);
```
##### case 1: delete parent

``` php
<?php
$parent = Model_Parent::find('first');
$parent->delete(true, true); //success!!
/*
mysql> select * from parents;
+----+---------------+------------+------------+------------+
| id | name          | created_at | updated_at | deleted_at |
+----+---------------+------------+------------+------------+
|  1 | 51da8cb0b1852 | 1373277360 | 1373277411 | 1373277411 |
+----+---------------+------------+------------+------------+

mysql> select * from children;
+----+---------------+-----------+------------+------------+------------+
| id | name          | parent_id | created_at | updated_at | deleted_at |
+----+---------------+-----------+------------+------------+------------+
|  1 | 51da8cb0b1c66 |         1 | 1373277360 | 1373277411 | 1373277411 |
+----+---------------+-----------+------------+------------+------------+
*/
```
##### case 2: delete child

``` php
<?php
$child = Model_Child::find('first');
$child->delete();
/*
Fuel\Core\Database_Exception [ 1048 ]: Column 'parent_id' cannot be null [ UPDATE `children` SET `deleted_at` = 1373278091, `parent_id` = null, `updated_at` = 1373278091 WHERE `id` = '1' ]
*/
```
### problem 2: Model_Soft cascade delete Model

d0f6c69

case `Model_Parent` extends `\Orm\Model_Soft`, and `Model_Child` extends `\Orm\Model`.

``` php
<?php
$parent = Model_Parent::find('first');
$parent->delete(true, true);
/*
Orm\RelationNotSoft [ Error ]: Both sides of the relation must be subclasses of Model_Soft or Model_Temporal if cascade delete is true. Model_Child was found instead.
*/
```

---

This pull-request fix these 2 problems, but I don't know extent of the impact.

### CODE REVIEW

**Comment by steadweb** [comment]
:+1:

Thanks @takyam-git this patch worked for me, I was experiencing "RelationNotSoft" exception being thrown, where some of our models have lots of many_many relations, which may not extend Model_Soft / Model_Temporal.

**Comment by WanWizard** [comment]
I don't agree with changes in the core Belongs_to class. And I don't think they are needed. Instead, the design of Model_Soft has to be looked at.

If a model has a belongs_to relation, the FK is always in the model itself. And since you are deleting that, there is no need to set anything to NULL.

**Comment by takyam-git** [comment]
so, when create new model that belongs to(example's Model_Child), 
if allow set null to `parent_id`,  then we can be create not relation model.

``` php
<?php
$child = Model_Child::forge();
// $child->parent = $parent <= I forgot add this row !
$child->name = 'hoge';
$child->save();
```

I think, when allow null, it can be create bugs easily. The RDBMS can protect from bug of insert data, by `NOT NULL`.

**Comment by takyam-git** [comment]
@WanWizard 
Soft deleted child can't be restore, because child record's paren_id is null.
Why set null to parent_id field on child's table ?

And legacy version ORM didn't set null to parent_id field.

``` sql
-- 1.5/develop:
UPDATE `children` SET `deleted_at` = '2013-07-24 05:51:50', `updated_at` = '2013-07-24 05:51:50' WHERE `id` = '38'
```

but now

``` sql
-- 1.7/develop:
UPDATE `children` SET `deleted_at` = '2013-07-24 05:52:14', `parent_id` = null, `updated_at` = '2013-07-24 05:52:14' WHERE `id` = '39'
```

These are same PHP code.

``` php
$model->delete(null, true);
```

I'm sorry my English If you feel a strange.

**Comment by WanWizard** [comment]
I don't know why the parent_id is now included, but if that is the problem, that should be fixed. And not worked around...

**Pull request closed without merging**
