### PR TITLE
Update classes/model.php

### PR DESCRIPTION
**Pull request by peter-fritchley**
fixes a return of the issue in #148

### CODE REVIEW

**Comment by WanWizard** [comment]
Any idea what caused the issue to reappear? 

I can't find any recent changes to this code, and it must come from somewhere. I want to avoid fixing something here that is caused elsewhere...

**Comment by peter-fritchley** [comment]
hmm.. seems that the change was reverted in response to https://github.com/fuel/orm/issues/171 - although in this case the fk is not set.

This causes problems because breaking the relation between models is implemented as setting the foreign key to null - meaning that these will be fetched by accessing the relation property for any newly created model.

**Comment by WanWizard** [comment]
From what I can see, and reading back the comments in the first issue, the point is that it needs a check if the FK is present before trying to fetch it? So it only fetches related objects when the FK !== null?

**Comment by peter-fritchley** [comment]
Ok, well in my case the relation is being fetched even though the FK === null.

Do you think it is the responsibility of the relation class to determine whether the FK is acceptable?

**Comment by WanWizard** [comment]
That's what I mean. The fix to this issue should be "do not fetch if FK === null".

The original code (and the one you propose the put back in) focuses on the state of the object (whether or not it has a PK) while it should check if there is an FK available for the relation being accessed, and only try to get it if there is one.

**Comment by peter-fritchley** [comment]
Ok, I'll add another pull request with it implemented within the relation classes.

Thanks.

**Comment by WanWizard** [comment]
No worries, I'm already on it. Just wanted to check if I was on the right track ;)

**Comment by WanWizard** [comment]
Just double checking: this is only an issue on a "belongs_to", right? It's the only relation where the model itself has the FK.

**Pull request closed without merging**
