### PR TITLE
Detailing available options in model and query doc blocks.

### PR DESCRIPTION
**Pull request by apdunston**
Added options keys to documentation for model and query to make them more available in documentation. This came from my hunt to find out there was a from_cache option.

### CODE REVIEW

**Comment by emlynwest** [comment]
Looks a little messy. Personally this is something I think should be in http://github.com/fuel/docs

**Comment by apdunston** [comment]
I agree that it is messy. I agree that it should also go there. But just a little clue here could save an hour of work for each adopter who stumbles on caching issues.

**Comment by emlynwest** [comment]
This is true but then perhaps just a note in the class' phpdoc would do.

**Comment by WanWizard** [comment]
If it's in the docs, everyone can find it. Nobody should have to dive into the code (ideally ;-) to find out how it works. So I agree it should be in the docs.

**Comment by apdunston** [comment]
I'll close this out for now. If I get time later, I'll write this up in the docs and do a pull request there. Thanks for the feedback, y'all.

**Pull request closed without merging**
