### PR TITLE
Fix error undefined index @ line 850:

### PR DESCRIPTION
**Pull request by purwandi**
Signed-off-by: Purwandi free6300@gmail.com

### CODE REVIEW

**Comment by purwandi** [comment]
When i create query from ORM like this

```
$student = Model_User::find('all',array(
    'related'   => array(
        'user_metadata',
        'user_group'    => array(
                'where' => array(
                    array('group_id',3)
                        )
               )
    )
));
```

I have got error 

http://d.pr/i/QUHL

**Comment by WanWizard** [comment]
First, your error messages shows line 850, while the actual line (and your change) is on line 860. So were you working with an older version?

Second, I'm not sure this is right. If $row[$pk_c] is not set at that moment, that can only mean $pk_c is still null, which means it couldn't find a primary key. Which would point towards a definition error in your model.

@jschreuder, your view?

**Comment by purwandi** [comment]
@WanWizard  ah yes, i working with FuelPHP 1.1

**Comment by purwandi** [comment]
I had to update to 1.1/develop, but I found the same problem when i use `is_null` .

http://d.pr/i/tGvs

**Comment by WanWizard** [comment]
Please post all models involved on http://scrp.at so I can have a look at it. It shouldn't do this if all keys are defined properly.

**Comment by purwandi** [comment]
OK, Here is my model
1. User http://scrp.at/bmD
2. Group http://scrp.at/bmE
3. User_Groups http://scrp.at/bmF
4. User_Metadata http://scrp.at/bmG

and my Controller

http://scrp.at/bmH

**Comment by WanWizard** [comment]
As I wrote before

> If $row[$pk_c] is not set at that moment, that can only mean $pk_c is still null, which means it couldn't find a primary key. Which would point towards a definition error in your model.

Both your User_Groups and User_Metadata tables do not have a primary key. ORM requires every model to have one!

**Comment by purwandi** [comment]
Thanks, this is my fault :)

**Pull request closed without merging**
