### PR TITLE
clear cached object(s) for memory leak

### PR DESCRIPTION
**Pull request by hackoh**
I wonder memory leaking

### CODE REVIEW

**Comment by hackoh** [comment]
sorry, i mistaked newline character...

**Comment by WanWizard** [comment]
Before you open it again, can you explain why you think there's a memory leak, and show us how you have determined there is one?

**Comment by hackoh** [comment]
When insert a record, the instance is always contains in $_cached_objects.
(classes/model.php:L1182)
For example, if I implement the "csv import" process, this will put pressure on memory.
Actually, I want to setup contains or not in config, But first, I want a way to explicitly remove.

(I reopened #194)

**Comment by WanWizard** [comment]
That is not a memory leak, that is by design. The ORM caches are records it retrieves.

You should not use the ORM for batch operations, it's not what it is designed for.

**Pull request closed without merging**
