### PR TITLE
Related #74 - Calls validation::run() with temporary callables

### PR DESCRIPTION
**Pull request by phil-lavin**

### CODE REVIEW

**Comment by phil-lavin** [comment]
This is associated with it:

https://github.com/fuel/core/pull/452

**Comment by jschreuder** [comment]
Improved a bit on your code I believe, let the checking be done by add_callable to simplify `Validation::run()`.

Changes are here: https://github.com/fuel/core/compare/846899e...cc27c23

**Comment by phil-lavin** [comment]
Hm. Not so much.

Whereas it was working fine with my code, it now fails the required validation on fields whose data is not submitted with POST. I get a legitimate failure from my own in model _validation_unique() function. At this time, I var_dump $this->password and a value is present. However, the validation is still failing.

Phil

**Comment by phil-lavin** [comment]
Also it seems the standard validation messages are also broken. I'm getting this:

Validation rule _validation_required failed for Password

**Comment by jschreuder** [comment]
@phil-lavin I haven't checked out yet why the rule names fail, but this one I'd already fixed locally.

**Comment by phil-lavin** [comment]
Testing now. Thanks :) @sicoanimal

**Comment by phil-lavin** [comment]
That's good now. Just the label thing left.

Thanks again :)

**Comment by jschreuder** [comment]
This should fix the issue with rules naming: https://github.com/fuel/core/commit/e29e1b6a7063667a9c73c471c9ea9d7dbefac200

**Comment by phil-lavin** [comment]
All is well. Cheers :)

**Pull request merged**
