### PR TITLE
Extended hasmany and manymany "get" method by handling "limit" condition

### PR DESCRIPTION
**Pull request by feldsam**
Signed-off-by: Kristián Feldsam feldsam@gmail.com

### CODE REVIEW

**Comment by emlynwest** [comment]
Looks ok but could you also add documentation for this over at https://github.com/fuel/docs please?

**Comment by WanWizard** [comment]
This the docs also need a big warning: this means results from this relation might be incomplete due to the limit, and this can have implications because the parent object is cached.

Before accepting this PR, we have to make sure that if you define two indentical relations, one with limit, one without, and you fetch the one with the limit first, the other one still produces the correct results (and I fear not).

**Comment by emlynwest** [comment]
Ah right, I had somehow forgotten about the caching.

**Comment by feldsam** [comment]
Hi, when you use already implemented where condition them you also get different result set. So?

**Comment by WanWizard** [comment]
As said, if it doesn't interfere, it's not a problem. Just needs a check, to make sure there are no compatibility issues created.

**Comment by feldsam** [comment]
I think that, if where condition doesn't interfere then limit condition doesn't interfere too.

**Comment by WanWizard** [comment]
As Morpheus said to Neo: "Don't think you are, know you are". ;-)

**Pull request closed without merging**
