### PR TITLE
Update slug.php

### PR DESCRIPTION
**Pull request by sagikazarmark**
Bad logical operator

### CODE REVIEW

**Comment by emlynwest** [comment]
This seems pretty pointless?

**Comment by sagikazarmark** [comment]
No it is not.

``` php
// Evaluates false
$overwrite = false or true;

// Evaluates true
$overwrite = false || true;
```

**Comment by emlynwest** [comment]
I see now. My mistake!

**Comment by okhayat** [comment]
Indeed. Is this a bug in PHP? Shouldn't OR act just like ||?!

**Comment by sagikazarmark** [comment]
@okhayat No, it isn't.

**Comment by okhayat** [comment]
But OR and || should be the same:
http://php.net/manual/en/language.operators.logical.php
$a or $b    Or  TRUE if either $a or $b is TRUE.
$a || $b    Or  TRUE if either $a or $b is TRUE.

**Comment by sagikazarmark** [comment]
@okhayat You are wrong. Read the page you linked more carefully. (Hint: Operator precedence)

**Comment by okhayat** [comment]
Yes. Operator precedence is confusing sometimes.
Good catch.

**Pull request merged**
