### PR TITLE
Add a method to get the primary key's as an array

### PR DESCRIPTION
**Pull request by xploSEoF**
This creates an array containing the relevant information for identification of the object. This could be used in many locations, specifically in my case, logging.

### CODE REVIEW

**Comment by emlynwest** [comment]
Functionality looks fine but please fix the coding style. Indent with tabs and `{}` on new lines please. Also possibly the function would be better named `get_pk_values()` or something akin to that to better describe what it does.

**Comment by WanWizard** [comment]
I'd say `get_pk()` would be enough, no need to add "array" or "values" to it? I'd only do that if you have or intend to have more methods starting with `get_pk`? 

Also, please update the documenation with the new method.

**Comment by emlynwest** [comment]
Only issue is that there's already a "get pk" method that returns the property names.

**Comment by WanWizard** [comment]
Then "values" seems better than "array", agreed.

**Comment by xploSEoF** [comment]
Or assoc, since values implies it is literally just the values...

**Comment by emlynwest** [comment]
I'd be happy with either `assoc` or `values`, both work for me.

**Comment by xploSEoF** [comment]
Where would you like documentation to be added? I can't find any of the functions on \Orm\Model in any of the documentation, with the exception of the very basic ones on the CRUD page.

**Comment by WanWizard** [comment]
You got a point, it does miss a method reference, so nowhere to add it...

**Comment by xploSEoF** [comment]
Was this not merged then, or has GitHub not identified the merge?

**Comment by WanWizard** [comment]
No, it wasn't. And it was a PR against a now outdated branch, so it couldn't be merged anymore.

**Comment by WanWizard** [comment]
Also, I wonder if that code (in particular the value reference) still works in PHP 7, as it always loops over a copy now.

@stevewest can you comment?

**Comment by xploSEoF** [comment]
Given my understanding over the PHP7 changes, this should continue to work.

Foreach loops in PHP < 7 loops over a copy, but with references when necessary. PHP >= 7 loops through the array itself.

**Comment by WanWizard** [comment]
Ok, then creating a new PR for 1.9/develop should not be a problem.

Regarding the method name, @stevewest stated `get_pk()` already existed, but I can''t find it?

**Pull request closed without merging**
