### PR TITLE
EAV properties added to to_array

### PR DESCRIPTION
**Pull request by sagikazarmark**
All properties of all related EAV relations are included in the array. EAV properties of relations are also included on the level of the relation.

### CODE REVIEW

**Comment by sagikazarmark** [comment]
Started in #303

**Comment by sagikazarmark** [comment]
There should be a publicly visible way to get the eav relations. Use case: you want to dynamically load EAV relations of several models in a query and you don't know the name of eav relations.

**Comment by WanWizard** [comment]
This can produce inconsistent output. 

When you have multiple EAV containers defined, __get() returns the first hit according to the order of the relations defined. In this code, the last hit wins.

And you still have the data in your array twice, as all EAV will also be in the array as related data. 

I'm not convinced of the use-case, you're the developer, how can you not know the name of the EAV relation?

**Comment by sagikazarmark** [comment]
The first problem's solution is simple: only set the value if it is not in the array. Before getting the values from the relations I process the EAV containers in order they are defined. So the same field don't have to be overwritten.

I think NOT having the EAV fields in the array IS an inconsistent output. If I use the model as an object, either getting a property or ArrayAccess way I get the EAV property. After to_array, I don't?

I have the data twice, and I think that having EAV container relations in to_array makes almost no sense, but removing it can break things.

But if you don't know and don't want to know whether you are getting keys from an array or an ArrayAcces, and you cannot get the same data (the same way), that is the definition of inconsistent output. (Eg. Twig, you don't have to know whether it is an array/object, you can get properties the same way.)

Last but not least: think about a controller which gets data from ANY model you give it. Eg. a blog module. You have a module for every post type. You can't be sure of the EAV name, unless YOU wrote all the models. But this last thing is actually useless or at least specific to my blog module.

**Comment by sagikazarmark** [comment]
If you don't like having the data twice, the I can make it a reference to the original array value for you. :smile:

**Comment by sagikazarmark** [comment]
I can imagine a third property in to array which tells the function whether you want to eav properties like eav properties or not.

**Comment by WanWizard** [comment]
I was about to suggest that:
- introduce a third parameter to indicate you want to include EAV or not (like $custom)
- make sure EAV relations are processed in reverse order, so the data will be the same as from get()
- filter the EAV relations from the included relations, no need to add the same data twice

**Comment by sagikazarmark** [comment]
Won't the last point break BC?

**Comment by sagikazarmark** [comment]
Any update on this?

**Pull request merged**
