### PR TITLE
Allow ordering on through table in many-many relationships

### PR DESCRIPTION
**Pull request by rob-mccann**
Previously one could only order on the `model_to`'s table.

Now, you can order on the `through` table too which allows for instances like below where the user wants to change the order that associated images are in.

This'll all need properly checking over for regressions by someone that knows more about the ORM's inner-workings than I.

``` php
class Model_Post extends \Orm\Model
{
protected static $_many_many = array(
    'images' => array(
        'conditions' => array(
            'order_by' => array(
                'images_posts.position' => 'asc',
            )
        )
    )
);

}
```

### CODE REVIEW

**Comment by WanWizard** [comment]
I have  mixed feelings about this one.

A through table should not contain anything but the two FK's. If it contains attributes too, it should have a Model associated with it, converting the many-2-many into two has-many's with the new model in the middle.

**Comment by emlynwest** [comment]
I think this would be a useful thing (not looked at the code yet). I have needed to be able to order/access the through table before when applying settings to the relation in this way.

**Comment by rob-mccann** [comment]
@wanwizard definitely see where you're coming from. It just seemed a bit like overkill to have a whole object just so I could order the relation :)

**Comment by emlynwest** [comment]
@rob-mccann If you have not already (not checked), could you create some docs for this too please?

**Comment by WanWizard** [comment]
Already done that. ;)

**Pull request merged**
