### PR TITLE
Support for custom names of PK column

### PR DESCRIPTION
**Pull request by ppatrik**
tables should have other PK names than 'id', eg. 'table_id'

### CODE REVIEW

**Comment by mikepmtl** [comment]
It already is supported.

protected static $_primary_key = array('aid');

http://fuelphp.com/docs/packages/orm/creating_models.html

**Comment by ppatrik** [comment]
yes but here in temporal model it was written to only accept `id`
see

classes/model/temporal.php line 153

```
        $query = static::query()
            ->where('id', $id)    <------- this is not correct
            ->where($timestamp_start_name, '<=', $timestamp)
            ->where($timestamp_end_name, '>', $timestamp);
```

**Comment by WanWizard** [comment]
You'll have to wait until @stevewest gets back, to asses it.

I'm pretty sure this has something to do with the complexities of compound PK's, something your PR doesn't address either.

**Comment by emlynwest** [comment]
Temporal is limited to "id" by design. It's a current limitation of the v1 temporal model and will be addressed in v2.

**Pull request closed without merging**
