### PR TITLE
multiple database support

### PR DESCRIPTION
**Pull request by lekoala**
basic support for multiple database

### CODE REVIEW

**Comment by jschreuder** [comment]
This looks good, I'll have to fully review & test it but I think you've pretty much covered it.

I have 2 small points already:
- it should be "connection" instead of "database" (because it uses another db connection, not another db)
- when relating models with different connections an exception should be thrown immediately

**Comment by jschreuder** [comment]
I only just noticed: you made the pull request to master, we don't accept requests to master - only to develop. Could you make another pull-request to the correct branch?

**Comment by patie** [comment]
i have suspicion that some problem with $this->connection in omr\classes\query.php because when i set   \
public static $_connection = 'connection2';
model still want working with default connection1 - for example when i call ::find()

**Comment by jschreuder** [comment]
Try using some caps & punctuation next time, that should make that collection of words more like actual sentences.

You're right, there was an ommission in my commit. It's been fixed.

**Comment by patie** [comment]
sry but my english is poor and in destination i use slashes but was be automatically striped

**Pull request closed without merging**
