### PR TITLE
error fix

### PR DESCRIPTION
**Pull request by hotlabs**
Undefined array key ""
PKGPATH/orm/classes/query.php @ line 1563

### CODE REVIEW

**Comment by WanWizard** [comment]
Can you give me an example in which a related record doesn't have a parent? 

What was `$pointers`, `$current` and `$parent` at that point?

**Comment by hotlabs** [comment]
error when using auth package, Ormauth,
	function Auth::verified()
			
        $parent = NULL
        $pointers = empty erray()
        $current = (str)'metadata'
php 8.0.3

**Comment by WanWizard** [comment]
and what is `$current` at that point? 

Because that suggests a first level related object, for root objects both `$current` and `$parent` should be `NULL`, and in that case, `$pointers[NULL]` should be created first and should therefore exist.

**Comment by hotlabs** [comment]
> и что `$current`в этот момент?
> 
> Поскольку это предполагает объект, связанный с первым уровнем, для корневых объектов оба `$current`и `$parent`должны быть `NULL`, и в этом случае `$pointers[NULL]`должны быть созданы в первую очередь и поэтому должны существовать.

    $current = (str)'metadata'

**Comment by WanWizard** [comment]
There is only one query in Ormauth that uses metadata:
````
				// find the user
				$this->user = \Model\Auth_User::query()
					->select(\Config::get('ormauth.table_columns', array()))
					->related('metadata')
					->where('username', '=', $username)
					->get_one();
````
which is a very simple and often occuring query. I'll see if I can reproduce it, because this error shouldn't happen.

**Comment by hotlabs** [comment]
Без названия

**Comment by hotlabs** [comment]
this error after install fuel and include auth package - without changing the code

**Comment by WanWizard** [comment]
I can reproduce it, looking at it now.

**Comment by hotlabs** [comment]
Yes, please fix this

**Comment by WanWizard** [comment]
Found the problem, fix is on the way, testing it now.

**Comment by WanWizard** [comment]
Fixed in 18dfbdeef0432c7de0bf2fb60bb44fd366785b90

**Pull request closed without merging**
